site_name: Portworx Enterprise Deployment and Configuration on OpenShift
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Kds Overview: modules/module-01-kds-overview.md
  - Module 2 - Install Portworx: modules/module-02-install-portworx.md
  - Module 3 - Storage Pools: modules/module-03-storage-pools.md
  - Module 4 - Demo Workloads: modules/module-04-demo-workloads.md
  - Module 5 - Failover: modules/module-05-failover.md
  - Module 6 - Pool Relocate: modules/module-06-pool-relocate.md
  - Module 7 - Auto Rebalancing: modules/module-07-auto-rebalancing.md
plugins:
- techdocs-core
